export type UUID = string;
export type ISODateString = string;

// The core scheduled event generated by the Orchestrator
export interface ScheduledReflectionEvent {
  id: UUID;
  user_id: UUID;
  status: 'PENDING' | 'EXECUTED' | 'CANCELLED';
  created_at: ISODateString;
  scheduled_for: ISODateString;

  // The directive for the future Executor agent
  ai_prompt: string;

  // The reasoning behind why this event was scheduled (for deduplication/pruning)
  reason: string;

  // Context pointers
  source_journal_entry_id: UUID;
  related_journal_ids: UUID[];        // Max 5
  related_chat_snippet_ids: UUID[];   // Max 5
}

// User Persona state, maintained and updated over time
export interface UserPersona {
  user_id: UUID;
  core_traits: string[];
  current_stressors: string[];
  active_goals: string[];
  last_updated: ISODateString;
}

// --- REPORTING TYPES ---

export interface ReportNode {
  id: string;
  title: string;
  description: string;
  source_journal_ids: UUID[];
  type: 'concept' | 'action' | 'emotion' | 'milestone';
  position?: { x: number; y: number }; // Optional for layout persistence
}

export interface ReportEdge {
  from: string;
  to: string;
  label?: string;
}

export interface InsightReport {
  id: UUID;
  user_id: UUID;
  title: string;
  summary: string;
  created_at: ISODateString;
  nodes: ReportNode[];
  edges: ReportEdge[];
  source_entry_ids: UUID[]; // The set of entries that triggered this report
}
