export type UUID = string;
export type ISODateString = string;

// The core scheduled event generated by the Orchestrator
export interface ScheduledReflectionEvent {
  id: UUID;
  user_id: UUID;
  status: 'PENDING' | 'EXECUTED' | 'CANCELLED';
  created_at: ISODateString;
  scheduled_for: ISODateString;

  // The directive for the future Executor agent
  ai_prompt: string;

  // Context pointers
  source_journal_entry_id: UUID;
  related_journal_ids: UUID[];        // Max 5
  related_chat_snippet_ids: UUID[];   // Max 5
}

// User Persona state, maintained and updated over time
export interface UserPersona {
  user_id: UUID;
  core_traits: string[];
  current_stressors: string[];
  active_goals: string[];
  last_updated: ISODateString;
}
